spring:
  application:
    name: microservice-discovery-eureka-ha

---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    # 指定dangprofile=peer1时，主机名是peer1
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: httlp://peer1:8761/eureka/
